<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>791c8084-8e28-4673-bf92-74eee62c7919</UserSecretsId>
  </PropertyGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\ApiService\ApiService.csproj" />
    <ProjectReference Include="..\Web\Web.csproj" />
  </ItemGroup>

  <ItemGroup Label="Package References">
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>

</Project>
